Document: ulatencyd
Title: Debian ulatencyd Manual
Author: <insert document author here>
Abstract: This manual describes what ulatencyd is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/ulatencyd/ulatencyd.sgml.gz

Format: postscript
Files: /usr/share/doc/ulatencyd/ulatencyd.ps.gz

Format: text
Files: /usr/share/doc/ulatencyd/ulatencyd.text.gz

Format: HTML
Index: /usr/share/doc/ulatencyd/html/index.html
Files: /usr/share/doc/ulatencyd/html/*.html
