#!/bin/bash

## Generates the applications.conf simple rules ##
## See scripts/cron.daily/99ulatencyd           ##

# BUGS: doess not handle whitespaces in paths to .desktop files

timeout=60	# flag timeout

output=${1:-/etc/ulatencyd/simple.d/applications.conf}

# mathing desktop files will be not parsed (extended regex without surrounding braces)
exclude_desktops_re="/autostart/|/app-install/|/gtk-modules|/locale/|/mimelnk/|/samples/|/examples/|/plugins/|/templates/"
exclude_desktops_re="$exclude_desktops_re|/desktoptheme/|/services/|/servicetypes/"	# KDE
exclude_desktops_re="$exclude_desktops_re|/helpers/"	#XFCE

EXEC_PATH="/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games"
FILE_CMD="file --brief -e apptype -e ascii -e encoding -e cdf -e compress -e tar -e elf --mime-type"
FILE_RES="application/x-executable"

#set -e

exec >$output

echo "# desktop applications"
echo "# Automatically generated by $0 on $(date --rfc-3339=seconds)"
echo

locate -er '\.desktop$' | egrep -v "($exclude_desktops_re)" |
	xargs grep -lF 'Type=Application' |
	xargs grep -lF 'Terminal=false' |
	xargs |
	while read files; do
		grep -h '^Exec=' $files | cut -b6-
		grep -h '^StartupWMClass=' $files | cut -b16-
	done |
		#cut -f1 -d' ' |
		sort -u |
		while read exec; do
			[ -z "$exec" ] && continue
			exec="$(chase "$(PATH=$EXEC_PATH which "$exec" 2>/dev/null)" 2>/dev/null)"
			[ -z "$exec" -o "$($FILE_CMD "$exec" 2>/dev/null)" != $FILE_RES ] && continue
			printf "%-30s application.starting instant=1 inherit=1 timeout=%d\n" "\"$exec\"" $timeout
		done |
sort -u

