#!/bin/bash

## Generates the applications.conf simple rules ##
## See scripts/cron.daily/99ulatencyd           ##

# BUGS: doess not handle whitespaces in paths to .desktop files

timeout=60	# flag timeout

output=${1:-/etc/ulatencyd/simple.d/applications.conf}

set -e

exec >$output

echo "# desktop applications"
echo "# Automatically generated by $0 on $(date --rfc-3339=seconds)"
echo

locate -er '\.desktop$' |
	xargs grep -lF 'Type=Application' |
	xargs grep -lF 'Terminal=false' |
	xargs |
	while read files; do
		grep -h '^Exec=' $files | cut -b6-
		grep -h '^StartupWMClass=' $files | cut -b16-
	done |
		cut -f1 -d' ' |
		sort -u |
		while read exec; do
			[ -z "$exec" ] && continue
			printf "%-30s application.starting instant=1 inherit=1 timeout=%d\n" "$exec" $timeout
		done |
sort -u

