.\"                                      Hey, EMACS: -*- nroff -*-
.TH ULATENCYD 1 "March 24, 2011"
.SH NAME
run-single-task \- executes program under SINGLE_TASK scheduler config
.SH SYNOPSIS
.B run-single-task
.RI COMMAND
.SH DESCRIPTION
\fBrun-single-task\fP is a simple shortcut to start a program using the SINGLE_TASK
scheduler configuration of the ulatencyd daemon.
.PP
\fBrun-single-task\fP is a shortcut for
.B
ulatency run-SINGLE_TASK COMMAND
.SH AUTHOR
ulatencyd was written by Daniel Poelzleithner <poelzi@poelzi.org>.
.PP
This manual page was written by Alessandro Ghedini <al3xbio@gmail.com>.
