.\"                                      Hey, EMACS: -*- nroff -*-
.TH ULATENCYD 1 "March 24, 2011"
.SH NAME
run-game \- executes program under GAME scheduler config
.SH SYNOPSIS
.B run-game
.RI [ COMMAND ]
.SH DESCRIPTION
\fBrun-game\fP is a simple shortcut to start a program using the GAME scheduler
configuration of the ulatencyd daemon.
.PP
\fBrun-game\fP is a shortcut for
.B
ulatency run-GAME COMMAND
.SH AUTHOR
ulatencyd was written by Daniel Poelzleithner <poelzi@poelzi.org>.
.PP
This manual page was written by Alessandro Ghedini <al3xbio@gmail.com>.
